### ISSUE TITLE
Slider: z-index

### ISSUE THREAD

**Issue by getflourish** [Frontify/fondue#854] opened 2022-06-27 13:43 UTC
The text items of the Slider component are rendered with `z-index: 10`. 

When implementing the slider in combination with a dialog, the slider text would appear above the dialog. 

I tried to fix it with `z-index: 1`, `z-index: 2`, … but then had to check what value I had to fight against to find out how to make it work. 

I bet there’s a reason for the z-index, but I can imagine that a smaller more sensible value would work, too :)

**Comment by jonasbuechel** [comment] 2022-07-27 07:11
@getflourish We're not able to reproduce it. Please provide us with a screenshot of the situation and the browser you're using.

**Comment by getflourish** [comment] 2022-07-27 14:31
I think it’s a specific issue that probably only occurs in combination with custom components that aren’t part of the design system. I was able to work around it. I think inside the Fondue system it probably will rarely ever be an issue. 

Some z-index values:

- Flyout: 100000
- Modal: 50
- Slider: 10
- Tooltip: 120000
- …

I think I was just surprised to even see a value on the `Slider` – for me it was just unexpected for the type of component. But on the other hand, it’s difficult to get right. 

Maybe a note in the docs could be nice, e.g. “This component creates a new stacking context“.

**Comment by ryancarville** [comment] 2023-10-10 13:51
Closing this `issue` and taking note to update docs with suggested context.

**Closed by ryancarville** 2023-10-10 13:51 UTC
Labels: feedback-needed
